ptw/urls.py
from django.urls import path
from . import views


app_name = 'ptw'
urlpatterns = [
    # ex: /ptw/smth/
    path('', views.IndexView.as_view(), name='home'),
    path('ptw/', views.PTWView.as_view(), name='ptw_index'),

    path('board/', views.board, name='board_index'),
    path('isolation/', views.IsolationActiveView.as_view(), name='active_index'),
    path('safe_entry/', views.SafeEntryView.as_view(), name='safe_entry'),
    path('inhibit/', views.InhibitView.as_view(), name='inhibit'),
    # ex: /ptw/5
    path('ptw/<int:ptw_id>/', views.permit, name='detail'),
    path('drills/', views.DrillsView.as_view(), name='drills'),
    path('drills/<int:drill_id>/', views.drill, name='drill'),
]

ptwproc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ptw.urls')),
]

ptw/models.py
import datetime
import tablib
from django.db import models
from django.utils import timezone
from import_export import resources
from .list_of_things import work_list, drill_types, drill_subtype


class Location(models.Model):
    name = models.CharField(max_length=100, unique=True)
    x = models.IntegerField()  # or models.FloatField() if you need decimal precision
    y = models.IntegerField()

    def __str__(self):
        return f'{self.name}'


class Restriction(models.Model):
    restriction = models.CharField(primary_key=True, max_length=3)
    restriction_details = models.CharField(max_length=200)
    is_self_restriction = models.BooleanField()

    def __str__(self):
        return f'{self.restriction}'


class SIMOPS(models.Model):
    work_type_1 = models.CharField(max_length=64, choices=work_list, blank=True)
    work_type_2 = models.CharField(max_length=64, choices=work_list, blank=True)
    are_conflicting = models.BooleanField()
    restriction = models.ForeignKey(Restriction, on_delete=models.PROTECT, db_column='restriction')

    def __str__(self):
        return f'{self.work_type_1} vs {self.work_type_2} is {self.restriction}'


class Isolation(models.Model):
    id = models.IntegerField(primary_key=True)
    status = models.CharField(max_length=10, choices=[
        ('created', 'created'),
        ('authorized', 'authorized'),
        ('long term', 'long term'),
        ('closed', 'closed'),
        ('cancelled', 'cancelled')], default='created')
    created_at = models.DateTimeField(auto_now=True)
    isolation_type = models.CharField(max_length=24, choices=[
        ('electrical', 'electrical'),
        ('mechanical', 'mechanical'),
        ('electrical & mechanical', 'electrical & mechanical')
    ], default='electrical')
    performing_authority = models.CharField(max_length=24, default='TBC')
    authorized_at = models.DateTimeField(default=timezone.now)
    closed_at = models.DateTimeField(default=timezone.now)
    equipment_description = models.CharField(max_length=24, default='TBC')
    equipment_maximo_tag = models.CharField(max_length=24, default='TBC')

    def __str__(self):
        return str(self.id)


class SafeEntry(models.Model):
    id = models.IntegerField(primary_key=True)
    status = models.CharField(max_length=10, choices=[
        ('created', 'created'),
        ('authorized', 'authorized'),
        ('closed', 'closed'),
        ('cancelled', 'cancelled')
    ], default='created')
    created_at = models.DateTimeField(auto_now=True)
    performing_authority = models.CharField(max_length=24, default='TBC')
    authorized_at = models.DateTimeField(default=timezone.now)
    closed_at = models.DateTimeField(default=timezone.now)
    space_description = models.CharField(max_length=24, default='TBC')
    space_maximo_tag = models.CharField(max_length=24, default='TBC')

    def __str__(self):
        return str(self.id)


class Inhibit(models.Model):
    id = models.IntegerField(primary_key=True)
    status = models.CharField(max_length=10, choices=[
        ('created', 'created'),
        ('authorized', 'authorized'),
        ('closed', 'closed'),
        ('cancelled', 'cancelled')
    ], default='created')
    created_at = models.DateTimeField(auto_now=True)
    performing_authority = models.CharField(max_length=24, default='TBC')
    authorized_at = models.DateTimeField(default=timezone.now)
    closed_at = models.DateTimeField(default=timezone.now)
    system_description = models.CharField(max_length=24, default='TBC')
    system_maximo_tag = models.CharField(max_length=24, default='TBC')
    ias_tags = models.CharField(max_length=60, default='TBC')
    block_or_suppress = models.CharField(max_length=10, choices=[
        ('block', 'block'),
        ('suppress', 'suppress')
    ], default='block')
    location = models.CharField(max_length=60, default='TBC')
    work_description = models.CharField(max_length=60, default='TBC')
    related_tags = models.CharField(max_length=60, default='TBC')

    def __str__(self):
        return str(self.id)

class PTW(models.Model):
    prefix = models.CharField(max_length=5, choices=[
        ('PTW', 'PTW'),
        ('HVPTW', 'HVPTW'),
        ('HVSFT', 'HVSFT'),
        ('Event', 'Event'),
    ], default='PTW')
    id = models.IntegerField(primary_key=True)
    status = models.CharField(max_length=10, choices=[
        ('created', 'created'),
        ('authorized', 'authorized'),
        ('suspended', 'suspended'),
        ('closed', 'closed'),
        ('cancelled', 'cancelled')]
                              )
    created_at = models.DateTimeField(auto_now=True)
    authorized_at = models.DateTimeField(default=timezone.now)
    closed_at = models.DateTimeField(default=timezone.now)
    planned_work_at = models.DateTimeField(default=timezone.now)
    work_description = models.CharField(max_length=64, default='TBC')
    work_type = models.CharField(max_length=64, choices=work_list, blank=True)
    work_location = models.ForeignKey(Location, on_delete=models.PROTECT)
    performing_authority = models.CharField(max_length=64, blank=True)
    permit_audit = models.IntegerField(default=0)
    ref_isolation = models.ForeignKey(Isolation, on_delete=models.PROTECT, blank=True, null=True)
    ref_safe_entry = models.ForeignKey(SafeEntry, on_delete=models.PROTECT, blank=True, null=True)
    ref_inhibit = models.ForeignKey(Inhibit, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return f'{self.prefix} {self.id}: {self.work_type} - {self.work_description} at' \
               f' {self.work_location} by {self.performing_authority} on {self.planned_work_at}'


class DrillType(models.Model):
    type = models.CharField(max_length=32, choices=drill_types)
    frequency = models.IntegerField(help_text="Drill frequency in days")
    def __str__(self):
        return self.type


class Drill(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.ForeignKey(DrillType, on_delete=models.CASCADE)
    sub_type = models.CharField(max_length=32, choices=drill_subtype, null=True, default=None)
    date = models.DateTimeField(default=timezone.now)
    date_next = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=128, default='Drill description:')
    long_description = models.CharField(max_length=1024, default='Long description:')
    personnel = models.CharField(max_length=1024, default='Personnel:')
    def __str__(self):
        return self.description


def get_total_audits(timedelta):
    # gets total sum of permit audits for given number of days back
    moment_in_the_past = timezone.now() - datetime.timedelta(days=timedelta)
    data = PTW.objects.filter(created_at__gte=moment_in_the_past).values_list('permit_audit', flat=True)
    return sum(data)


def import_csv():
    with open('ptw/static/ptw/data/restrictions.csv', 'r') as fh:
        imported_data = tablib.Dataset().load(fh)
        resource = resources.modelresource_factory(model=SIMOPS)()
        result = resource.import_data(imported_data, dry_run=False)
        print(result.has_errors())

ptw/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.exceptions import ObjectDoesNotExist

from .models import PTW, Isolation, Inhibit, SafeEntry, get_total_audits, SIMOPS, Restriction, Drill


# Create your views here.
class IndexView(generic.TemplateView):
    template_name = 'ptw/index.html'
    extra_context = {'audits': str(get_total_audits(7))}


class PTWView(generic.ListView):
    template_name = 'ptw/ptw_index.html'
    context_object_name = 'latest_active_list'

    def get_queryset(self):
        """Return records"""
        return PTW.objects.filter(
            Q(status__exact='authorized') | Q(status__exact='created') | Q(status__exact='suspended')
        )


def board(request):
    # Fetch active work permits with related location data
    permits = PTW.objects.filter(status='authorized').select_related('work_location')

    # Prepare location data for the template
    locations = [
        {
            'name': permit.work_location.name,
            'x': permit.work_location.x,
            'y': permit.work_location.y,
            'permit_id': permit.id,
            # Add any other permit data you need
        }
        for permit in permits
    ]

    context = {
        'locations': locations,
    }

    return render(request, 'ptw/board.html', context)


class IsolationActiveView(generic.ListView):
    template_name = 'ptw/isolation_index.html'
    context_object_name = 'active_isolations'

    def get_queryset(self):
        return Isolation.objects.filter(
            Q(status__exact='authorized') | Q(status__exact='created') | Q(status__exact='long term')
        )


class SafeEntryView(generic.ListView):
    template_name = 'ptw/safeentry_index.html'
    context_object_name = 'safeentry'

    def get_queryset(self):
        return SafeEntry.objects.filter(
            Q(status__exact='authorized') | Q(status__exact='created')
        )


class InhibitView(generic.ListView):
    template_name = 'ptw/inhibit_index.html'
    context_object_name = 'inhibit'

    def get_queryset(self):
        return Inhibit.objects.filter(
            Q(status__exact='authorized') | Q(status__exact='created')
        )

class DrillsView(generic.ListView):
    template_name = 'ptw/drill_register.html'
    context_object_name = 'drill'

    def get_queryset(self):
        return Drill.objects.all()


def permit(request, ptw_id):
    this_permit = get_object_or_404(PTW, pk=ptw_id)
    active_ptws = PTW.objects.filter(status__exact='authorized')
    simops = SIMOPS.objects.all()
    restrictions = []
    descriptions = []
    for active in active_ptws:
        try:
            obj = simops.get(work_type_1__exact=this_permit.work_type, work_type_2__exact=active.work_type)
            desc = Restriction.objects.get(restriction__exact=obj.restriction)
            restrictions.append(obj)
            descriptions.append(desc)
        except ObjectDoesNotExist:
            no_rest = Restriction.objects.get(restriction__exact='R0')
            restrictions.append(f'no additional measures required for {this_permit.id}')
            descriptions.append(no_rest)

    context = {'this_permit': this_permit,
               'active_ptws': active_ptws,
               'simops': simops,
               'restrictions': restrictions,
               'descriptions': descriptions,
               }
    return render(request, 'ptw/detail.html', context)


def drill(request, drill_id):
    this_drill = get_object_or_404(Drill, pk=drill_id)
    context = {'this_drill': this_drill,
               'type': this_drill.type,
               'sub_type': this_drill.sub_type,
               'date': this_drill.date,
               'date_next': this_drill.date_next,
               'description': this_drill.description,
               'long_description': this_drill.long_description,
               'personnel': this_drill.personnel,
               }
    return render(request, 'ptw/drill_report.html', context)

ptw/templates/ptw/board.html
<!-- templates/work_locations.html -->
{% extends 'ptw/nav.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="EN" >
<head>
    <title>Work Locations</title>
    <link rel="stylesheet" href="{% static 'ptw/css/styles.css' %}">
</head>
<body>
    <div id="scheme-container">
        <img src="{% static 'ptw/images/scheme.png' %}" id="scheme" alt="Work Scheme">
        <div id="markers"></div>
    </div>

    <script>
        // Pass the locations data to JavaScript
        const locations = {{ locations|safe }};
        const scheme = document.getElementById('scheme');
        const markersContainer = document.getElementById('markers');

        scheme.onload = function() {
            const schemeWidth = scheme.naturalWidth;
            const schemeHeight = scheme.naturalHeight;
            const displayedWidth = scheme.width;
            const displayedHeight = scheme.height;

            const widthScale = displayedWidth / schemeWidth;
            const heightScale = displayedHeight / schemeHeight;

            locations.forEach(location => {
                const marker = document.createElement('div');
                marker.className = 'marker';
                marker.style.left = (location.x * widthScale) + 'px';
                marker.style.top = (location.y * heightScale) + 'px';
                marker.title = `${location.name} (Permit ID: ${location.permit_id})`;
                markersContainer.appendChild(marker);
            });
        };

        // Handle window resize to reposition markers
        window.addEventListener('resize', function() {
            markersContainer.innerHTML = '';
            scheme.onload();
        });
    </script>
</body>
</html>
{% endblock %}

ptw/templates/ptw/detail.html
{% extends 'ptw/nav.html' %}

{% block content %}
<div class="col-md p-4">
            <h2 class="text-success">{{ this_permit.prefix }} {{ this_permit.id }} Details</h2>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Field</th>
                            <th scope="col">Description</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        <tr>
                            <th scope="row">ID & Status:</th>
                            <td>{{ this_permit.prefix }}{{ this_permit.id }} is currently {{ this_permit.status }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Performed by:</th>
                            <td>{{ this_permit.performing_authority }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Work description:</th>
                            <td>{{ this_permit.work_description }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Work type:</th>
                            <td>{{ this_permit.work_type }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Work location:</th>
                            <td>{{ this_permit.work_location }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Created at:</th>
                            <td>{{ this_permit.created_at }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Authorized at:</th>
                            <td>{{ this_permit.authorized_at }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Closed at:</th>
                            <td>{{ this_permit.authorized_at }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Reference IC</th>
                            <td>{{ this_permit.ref_isolation }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Reference SEC</th>
                            <td>{{ this_permit.ref_safe_entry }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Reference Inhibit</th>
                            <td>{{ this_permit.ref_inhibit }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Audits performed</th>
                            <td>{{ this_permit.permit_audit }}</td>
                        </tr>
                    </tbody>
                </table>
</div>
<h3 class="fst-italic text-success p-4">PTW conflicts and safety measures:</h3>
<div class="container">
    <div class="row justify-content-start gy-5 text-truncate">
        <div class="col-sm bg-secondary bg-opacity-25 rounded p-4">
            <h2>Active Permits:</h2>
            {% if active_ptws %}
                {% for permit in active_ptws %}
                    <p>{{ permit.prefix }}{{ permit.id }} {{ permit.work_description }} by {{ permit.performing_authority }} </p>

                {% endfor %}
            {% endif %}
        </div>
        <div class="col-sm bg-light rounded p-4">
            <h2>SIMOPS matrix:</h2>
                {% if restrictions %}
                    {% for item in restrictions %}
                         <p>{{ item }}</p>
                    {% endfor %}
                {% endif %}
        </div>
        <div class="col-sm bg-info rounded p-4">
        <h2>Safety measures:</h2>
        {% if descriptions %}
             {% for desc in descriptions %}
                 <p class="text fst-italic">{{ desc.restriction }} = {{ desc.restriction_details }}</p>
             {% endfor %}
        {% endif %}
        </div>
</div>
</div>
{% endblock %}

ptw/templates/ptw/drill_register.html
{% extends 'ptw/nav.html' %}


{% block content %}

<h2>Drill Register</h2>

<div class="table-responsive">
<table class="table table-striped table-hover">
<thead>
      <tr>
          <th scope="col">ID</th>
          <th scope="col">Type</th>
          <th scope="col">Sub-type</th>
          <th scope="col">Last held</th>
          <th scope="col">Next due</th>
          <th scope="col">Description</th>
      </tr>
</thead>
{% if drill %}
    {% for item in drill %}
        <tbody class="table-group-divider">
        <tr>
            <td><a href="{% url 'ptw:drill' item.id %}">{{ item.id }}</a></td>
            <td>{{ item.type }}</td>
            <td>{{ item.sub_type }}</td>
            <td>{{ item.date }}</td>
            <td>{{ item.date_next }}</td>
            <td>{{ item.description }}</td>
        </tr>
        </tbody>
    {% endfor %}
{% else %}
    <p>No drills have been registered.</p>
{% endif %}
</table>
</div>

{% endblock %}

ptw/templates/ptw/drill_report.html
{% extends 'ptw/nav.html' %}

{% block content %}
<div class="col-md p-4">
            <h2 class="text-success">{{ this_drill.description }} on {{ this_drill.date }} details:</h2>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Field</th>
                            <th scope="col">Description</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        <tr>
                            <th scope="row">ID:</th>
                            <td>{{ this_drill.id }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Type and Subtype:</th>
                            <td>{{ this_drill.type }} {{ this_drill.sub_type }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Date performed:</th>
                            <td>{{ this_drill.date }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Date next due:</th>
                            <td>{{ this_drill.date_next }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Long description:</th>
                            <td>{{ this_drill.long_description }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Personnel involved:</th>
                            <td>{{ this_drill.personnel }}</td>
                        </tr>
                    </tbody>
                </table>
</div>
{% endblock %}

ptw/templates/ptw/index.html
{% extends 'ptw/nav.html' %}


{% block content %}
<div class="container-lg">
<figure class="figure">
        <blockquote class="blockquote">
        {% lorem 1 p %}

        <p class="text-success"> Performed {{ audits }} PTW audits last week</p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Plato in <cite title="Source Title">State</cite>
        </figcaption>
</figure>
</div>

{% endblock %}

ptw/templates/ptw/inhibit_index.html
{% extends 'ptw/nav.html' %}


{% block content %}

<h2>Inhibits Register</h2>

<div class="table-responsive">
<table class="table table-striped table-hover">
<thead>
      <tr>
          <th scope="col">Number</th>
          <th scope="col">Created at</th>
          <th scope="col">Performing Authority</th>
          <th scope="col">System Description</th>
          <th scope="col">Maximo Tag</th>
          <th scope="col">IAS Tag</th>
          <th scope="col">Block/Suppress</th>
          <th scope="col">Status</th>
      </tr>
</thead>
{% if inhibit %}

            {% for item in inhibit %}
                <tbody class="table-group-divider">
                    <tr>
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.created_at }}</td>
                        <td>{{ item.performing_authority }}</td>
                        <td>{{ item.system_description }}</td>
                        <td>{{ item.system_maximo_tag }}</td>
                        <td>{{ item.ias_tag }}</td>
                        <td>{{ item.block_or_suppress }}</td>
                        <td class="{% if item.status == "authorized" %}{{ 'text-bg-success' }}
                                    {% elif item.status == "created" %}{{ 'text-bg-info' }}
                                    {% else %}{{ 'text-bg-warning' }}
                                    {% endif %}">{{ item.status }}</td>
                    </tr>
                </tbody>
            {% endfor %}

{% else %}
    <p>No inhibits are currently active.</p>
{% endif %}
</table>
</div>

{% endblock %}

ptw/templates/ptw/isolation_index.html
{% extends 'ptw/nav.html' %}


{% block content %}

<h2>Isolation Register</h2>

<div class="table-responsive">
<table class="table table-striped table-hover" data-toggle="table">
<thead>
      <tr>
          <th scope="col">Number</th>
          <th scope="col">Created at</th>
          <th scope="col">Performing Authority</th>
          <th scope="col">Type</th>
          <th scope="col">Description</th>
          <th scope="col">Maximo Tag</th>
          <th scope="col">Status</th>
      </tr>
</thead>

{% if active_isolations %}

            {% for isolation in active_isolations %}
                <tbody class="table-group-divider">
                    <tr>
                        <th scope="row">{{ isolation.id }}</th>
                        <td>{{ isolation.created_at }}</td>
                        <td>{{ isolation.performing_authority }}</td>
                        <td>{{ isolation.isolation_type }}</td>
                        <td>{{ isolation.equipment_description }}</td>
                        <td>{{ isolation.equipment_maximo_tag }}</td>
                        <td class="{% if isolation.status == "authorized" %}{{ 'text-bg-success' }}
                                    {% elif isolation.status == "created" %}{{ 'text-bg-info' }}
                                    {% else %}{{ 'text-bg-warning' }}
                                    {% endif %}">{{ isolation.status }}</td>
                    </tr>
                </tbody>
            {% endfor %}

{% else %}
    <p>No isolations are currently active.</p>
{% endif %}
</table>
</div>

{% endblock %}

ptw/templates/ptw/nav.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
      <meta charset="utf-8" />
      <title>Stena Home</title>
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'ptw/css/bootstrap.css' %}"/>
      <script src={% static 'ptw/js/bootstrap.js' %}></script>

  </head>

<nav class="navbar navbar-expand-lg">
  <div class="container-xl">
    <a class="navbar-brand align-top"
       href="{% url 'admin:index' %}">
        <img src="{% static 'ptw/images/rocket-takeoff.svg' %}" alt="Admin" width="32" height="32">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
          <form class="container-fluid justify-content-start">
            <a class="btn btn-outline-primary" role="button" href="{% url 'ptw:home' %}">Home</a>
            <a class="btn btn-outline-secondary" role="button" href="{% url 'ptw:ptw_index' %}">PTW</a>
            <a class="btn btn-outline-success" role="button" href="{% url 'ptw:active_index' %}">Isolations</a>
            <a class="btn btn-outline-warning" role="button" href="{% url 'ptw:safe_entry' %}">Safe Entries</a>
            <a class="btn btn-outline-info" role="button" href="{% url 'ptw:inhibit' %}">Inhibits</a>
            <a class="btn btn-outline-danger" role="button" href="{% url 'ptw:drills' %}">Drill Register</a>
            <a class="btn btn-outline-dark" role="button" href="{% url 'ptw:board_index' %}">LIVE PTW BOARD</a>
          </form>
      </div>
    </div>
      <div class="text">{% now "jS \o\f F Y \w\e\e\k \# W" %}</div>
  </div>
</nav>

<body>
<div class="container-xl">
    {% block content %}

    {% endblock %}
</div>
</body>

</html>

ptw/templates/ptw/ptw_index.html
{% extends 'ptw/nav.html' %}
{% block content %}

<h2>PTW Register</h2>
<div class="table-responsive">
<table class="table table-striped table-hover">
<thead>
      <tr>
          <th scope="col">Prefix</th>
          <th scope="col">Number</th>
          <th scope="col">Created at</th>
          <th scope="col">Performing Authority</th>
          <th scope="col">Type</th>
          <th scope="col">Location</th>
          <th scope="col">Description</th>
          <th scope="col">Status</th>
      </tr>
</thead>
{% if latest_active_list %}

            {% for ptw in latest_active_list %}
                <tbody class="table-group-divider">
                    <tr>
                        <th scope="row">{{ ptw.prefix }}</th>
                        <td><a href="{% url 'ptw:detail' ptw.id %}">{{ ptw.id }}</a></td>
                        <td>{{ ptw.created_at }}</td>
                        <td>{{ ptw.performing_authority }}</td>
                        <td>{{ ptw.work_type }}</td>
                        <td>{{ ptw.work_location }}</td>
                        <td>{{ ptw.work_description }}</td>
                        <td class="{% if ptw.status == "authorized" %}{{ 'text-bg-success' }}
                                    {% elif ptw.status == "created" %}{{ 'text-bg-info' }}
                                    {% else %}{{ 'text-bg-warning' }}
                                    {% endif %}">{{ ptw.status }}</td>
                    </tr>
                </tbody>
            {% endfor %}

{% else %}
    <p>No ptw are currently active.</p>
{% endif %}
</table>
</div>
{% endblock %}

ptw/templates/ptw/safeentry_index.html
{% extends 'ptw/nav.html' %}
{% block content %}

<h2>Safe Entry Register</h2>


<div class="table-responsive">
<table class="table table-striped table-hover">
<thead>
      <tr>
          <th scope="col">Number</th>
          <th scope="col">Created at</th>
          <th scope="col">Performing Authority</th>
          <th scope="col">Space Description</th>
          <th scope="col">Maximo Tag</th>
          <th scope="col">Status</th>
      </tr>
</thead>
{% if safeentry %}

            {% for item in safeentry %}
                <tbody class="table-group-divider">
                    <tr>
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.created_at }}</td>
                        <td>{{ item.performing_authority }}</td>
                        <td>{{ item.space_description }}</td>
                        <td>{{ item.space_maximo_tag }}</td>
                        <td class="{% if item.status == "authorized" %}{{ 'text-bg-success' }}
                                    {% elif item.status == "created" %}{{ 'text-bg-info' }}
                                    {% else %}{{ 'text-bg-warning' }}
                                    {% endif %}">{{ item.status }}</td>
                    </tr>
                </tbody>
            {% endfor %}

{% else %}
    <p>No safe entries are currently active.</p>
{% endif %}
</table>
</div>

{% endblock %}